name: "Rust CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0

  test:
    needs: clippy
    strategy:
      matrix:
        triple:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-gnu" }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}

  docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: darbiadev/.github/.github/workflows/github-pages-rust-doc.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0
