name: "Rust - Publish to crates.io"

on:
  release:
    types: [ released ]

jobs:
  publish:
    uses: darbiadev/.github/.github/workflows/rust-crates-io-publish.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
