name: "Rust - Publish to crates.io"

on:
  release:
    types: [ released ]

jobs:
  publish:
    uses: darbiadev/.github/.github/workflows/rust-crates-io-publish.yaml@91dda16028f109ac78016dd740206fd109740068 # v15.0.0
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
